openapi: 3.1.0
info:
  title: Slack Proxy API
  version: 1.0.0
  description: GPT middleware to fetch messages from Slack on behalf of the user.
servers:
  - url: https://slack-chatgpt-connection.delightfulflower-924a0481.westus2.azurecontainerapps.io
    description: Azure-hosted Slack proxy API

paths:
  /slack/messages:
    get:
      operationId: getMessages
      summary: Get Slack messages from a channel or DM
      parameters:
        - name: user_id
          in: query
          required: true
          schema:
            type: string
        - name: channel
          in: query
          required: true
          schema:
            type: string
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: Message history
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  messages:
                    type: array
                    items:
                      type: object
